#!/bin/bash

## Setup ##
setup(){
  export HOME_DIR=`pwd`
  export UTIL_DIR=`pwd`"/util"
  export LOG_COLLECT_DIR=`pwd`"/log_collector"

  . $UTIL_DIR/util.sh
  . $LOG_COLLECT_DIR/icpd-logcollector-master-nodes.sh
}

setup $@
local name_space=zen
local tempdir=$logs_dir

cmd="kubectl -n $name_space logs dv-0 -c init-sysctl"
get_log_by_cmd $tempdir dv_file_in_persistent_volumes "$cmd"
