{
 "title": "IBM Cloud Private for Data Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (alertid, alertname) (ALERTS {alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Top 5 CPU consuming Services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(max(label_join(kube_pod_labels{namespace=\"zen\"},\"label_k8s_app\",\"\",\"label_app\")) by (label_app,pod) \n* \non(pod) \n\ngroup_right(label_app) \n\nlabel_replace(sum(rate(container_cpu_usage_seconds_total{namespace=\"zen\"}[5m])) by (pod_name),\"pod\",\"$1\",\"pod_name\",\"(.+)\")) by (label_app))",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "Top 5 memory consuming services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes{namespace=\"zen\",container_name!=\"POD\", pod_name !=\"\"}) by (pod_name) ) / 10^9",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU utilization per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance, nodename)(irate(node_cpu_seconds_total{mode!='idle'}[5m]))) *100  * on (instance) group_left (nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "sum by (instance)(ALERTS{alertname=\"HighResvCPU\",alertstate=\"firing\"}) * on (instance) group_left (nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory utilization per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * ((node_memory_MemTotal_bytes - (node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes))/node_memory_MemTotal_bytes) * on (instance) group_left (nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk I/O utillization per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " avg by (instance) (irate(node_disk_io_time_seconds_total[5m])/1000) * on (instance) group_left (nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Network I/O per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": " avg by (instance) ((irate(node_network_receive_bytes_total[5m]) + irate(node_network_transmit_bytes_total[5m])) ) * on (instance) group_left (nodename) node_uname_info / 10^3",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}